### ISSUE TITLE
Not triggering build checks after /rebase comment is processed

### ISSUE THREAD

**Issue by flcdrg** [peter-evans/rebase#75]
I've added the rebase command workflows to a private repository:

rebase-command.yml

```yaml
name: rebase-command
on:
  repository_dispatch:
    types: [rebase-command]
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v1
        id: rebase
        with:
          head: ${{ github.event.client_payload.pull_request.head.label }}
      - name: Add reaction
        if: steps.rebase.outputs.rebased-count == 1
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT_REPO_FULL }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
```

rebase-command-dispatch.yml

```yaml
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT_REPO_FULL }}
          commands: rebase
          permission: write
          issue-type: pull-request
```

The PAT has full repo permissions.

The `/rebase` command is processed and the rebased branch is successfully force pushed for the pull request, but none of the build checks are fired. It effectively means the pull request is stuck (as those checks are mandatory). 

eg.
![image](https://user-images.githubusercontent.com/384747/118096210-349b4700-b410-11eb-9338-92d1082f66f8.png)

Wondering if you have any ideas why that would be the case?
