### ISSUE TITLE
Run peter-evans/rebase@v1.0.5

### ISSUE THREAD

**Issue by splincode** [peter-evans/rebase#86]
```
Run peter-evans/rebase@v1.0.5
  with:
    token: ***
    base: main
    repository: TinkoffCreditSystems/taiga-ui
(node:1734) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: Cannot read property 'url' of null
```

https://github.com/TinkoffCreditSystems/taiga-ui/runs/3689024496

**Comment by peter-evans** [comment]
Hi @splincode 

I'm not sure why this is happening. Would you be able to turn on debug messages to help identify the problem. You can turn them on by adding the GitHub secret `ACTIONS_STEP_DEBUG` and setting it to `true`.

**Comment by splincode** [comment]
```
name: Rebase all pull requests on push to the base branch

on: [push]

jobs:
    rebase:
        runs-on: ubuntu-latest
        env:
            ACTIONS_RUNNER_DEBUG: true
        steps:
            - uses: peter-evans/rebase@v1
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  base: main

```

you mean?
