### ISSUE TITLE
Feature: skip rebase by name PR

### ISSUE THREAD

**Issue by splincode** [peter-evans/rebase#95]
We want skip rebase for PR when:
- is draft
- support by regexp pattern

![image](https://user-images.githubusercontent.com/12021443/136334448-ced59f8a-629c-46ae-af4e-35973ec0da96.png)

**Comment by splincode** [comment]
new options:

```
with:
    skip_drafts: true
```

**Comment by peter-evans** [comment]
@splincode I've added new features that are available in the latest release `v1.2.0` / `v1`.

To exclude drafts:
```yml
      - uses: peter-evans/rebase@v1
        with:
          exclude-drafts: true
```

To exclude forks use the head filter with a wildcard for the ref.
```yml
      - uses: peter-evans/rebase@v1
        with:
          head: 'TinkoffCreditSystems:*'
```

As for the title pattern idea, I'm not sure if I want to add that feature. There is already an `exclude-labels` feature that can be used to cover that type of use case. Simply label pull requests with a specific label that you exclude. In a separate workflow you could even automate adding a label to a pull request if the title matches a pattern. I'm sure there are other actions which already can do this.
```yml
      - uses: peter-evans/rebase@v1
        with:
          exclude-labels: |
            no-rebase
            dependencies
```

Thanks for the feature ideas.
